version: '3.1'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=000000
      - POSTGRES_DB=demo_node_api